repos:
  - repo: local
    hooks:
    - id: black
      name: black
      entry: ./.venv/bin/black
      language: python
      types_or: [python, pyi]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.337
    hooks:
    - id: pyright
