version: 2.1

orbs:
  docker: circleci/docker@2.8.0

commands:
  generate-version-number-dev:
    steps:
    - run:
        command: |
          PIPELINE_NUMBER=<< pipeline.number >>
          if git describe --tags --abbrev=0; then TAG=$(git describe --tags --abbrev=0); else TAG=v0.0.0; fi
          VERSION=${TAG#v}
          echo "NEXT_VERSION=$(echo "$VERSION" | awk 'BEGIN{FS=OFS="."} {$3+=1} 1')rc${PIPELINE_NUMBER}" >> $BASH_ENV
          source $BASH_ENV
        name: Generate dev version number
  generate-version-number-prod:
    steps:
    - run:
        command: |
          if git describe --tags --abbrev=0; then TAG=$(git describe --tags --abbrev=0); else exit 1; fi
          echo "VERSION_TAG=${TAG#v}" >> $BASH_ENV
          source $BASH_ENV
        name: Generate prod version number

jobs:
  build-and-push:
    executor: machine
    machine:
      image: ubuntu-2204:current
    parameters:
      docker_hub_repository:
        type: string
      code_version:
        type: string
    steps:
      - checkout
      - docker/check:
          use-docker-credentials-store: true
      - docker/build:
          step-name: Build service image
          path: service
          docker-context: service
          use-buildkit: true  # to build only the required stages
          extra_build_args: --build-arg code_version=<< parameters.code_version >>
          image: montecarlodata/<< parameters.docker_hub_repository >>
          tag: latest,<< parameters.code_version >>
      - docker/push:
          image: montecarlodata/<< parameters.docker_hub_repository >>
          tag: latest,<< parameters.code_version >>

  run-test-docker:
    executor: machine
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - docker/build:
          path: service
          docker-context: service
          image: mcd/sna-agent-tests
          use-buildkit: true  # to build only the required stages
          extra_build_args: --target tests
          step-name: Run tests in docker build

workflows:
  version: 2

  build-sna:
    jobs:
      - run-test-docker:
          # run for all tags and branches, we need to add this so the job is available for build-and-push-prod
          filters:
            tags:
              only: /.*/
      - build-and-push:
          name: build-and-push-dev
          docker_hub_repository: prerelease-sna-agent
          code_version: ${NEXT_VERSION}
          pre-steps:
            - checkout
            - generate-version-number-dev
          context:
            - docker
          requires:
            - run-test-docker
          filters:
            branches:
              only:
                - dev
      - build-and-push:
          name: build-and-push-prod
          docker_hub_repository: sna-agent
          code_version: ${VERSION_TAG}
          pre-steps:
            - checkout
            - generate-version-number-prod
          context:
            - docker
          requires:
            - run-test-docker
          filters: # run only for tags starting with v, don't run for branches
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
