SET user_name='<user_name>';

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS mc_app_role;

CREATE DATABASE IF NOT EXISTS mc_app_data;
GRANT OWNERSHIP ON DATABASE mc_app_data TO ROLE mc_app_role COPY CURRENT GRANTS;

GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE mc_app_role;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE mc_app_role;
GRANT CREATE APPLICATION PACKAGE ON ACCOUNT TO ROLE mc_app_role;
GRANT CREATE APPLICATION ON ACCOUNT TO ROLE mc_app_role;
GRANT CREATE COMPUTE POOL ON ACCOUNT TO ROLE mc_app_role WITH GRANT OPTION;
-- GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE mc_app_role WITH GRANT OPTION;

GRANT ROLE mc_app_role TO USER IDENTIFIER($user_name);

GRANT USAGE ON WAREHOUSE APP_DEV_WH TO ROLE MC_APP_ROLE