CONFIG_USE_CONNECTION_POOL = "USE_CONNECTION_POOL"
CONFIG_CONNECTION_POOL_SIZE = "CONNECTION_POOL_SIZE"
CONFIG_QUERIES_RUNNER_THREAD_COUNT = "QUERIES_RUNNER_THREAD_COUNT"
CONFIG_OPS_RUNNER_THREAD_COUNT = "OPS_RUNNER_THREAD_COUNT"
CONFIG_PUBLISHER_THREAD_COUNT = "PUBLISHER_THREAD_COUNT"
CONFIG_USE_SYNC_QUERIES = "USE_SYNC_QUERIES"
CONFIG_STAGE_NAME = "STAGE_NAME"

ALL_CONFIG_KEYS = [
    CONFIG_USE_CONNECTION_POOL,
    CONFIG_CONNECTION_POOL_SIZE,
    CONFIG_QUERIES_RUNNER_THREAD_COUNT,
    CONFIG_OPS_RUNNER_THREAD_COUNT,
    CONFIG_PUBLISHER_THREAD_COUNT,
    CONFIG_USE_SYNC_QUERIES,
    CONFIG_STAGE_NAME,
]
